# ipsec.conf - strongSwan IPsec configuration file

config setup
	# strictcrlpolicy=yes
	uniqueids = yes

conn %default
	dpdaction=clear
	dpddelay=35s
	dpdtimeout=180s

conn ipsec-rw
	keyexchange=ikev1
	ikelifetime=8h
	keyingtries=2
	authby=xauthpsk
	left=%defaultroute
	leftsubnet=0.0.0.0/0
	leftauth=psk
	leftfirewall=yes
	xauth=server
	right=%any
	rightsourceip=%dhcp
	rightauth=psk
	rightauth2=xauth
	auto=add

conn l2tp
	left=%any
	right=%any
	auto=add
	rekey=yes
	leftprotoport=17/1701
	rightprotoport=17/%any
	keyingtries=2
	keyexchange=ikev1
	leftauth=psk
	rightauth=psk
	ikelifetime=8h
	ike=aes128-sha1-modp1536
	esp=aes128-sha1
	type=transport
