#!/bin/sh
#
# Luxul system config

# Create uuid if it does not exist
uuid=$(nvram get cpeuuid)
if [ -z "$uuid" ]; then
	# This device never had CPE UUID, generate a new one
	uuid=$(cat /proc/sys/kernel/random/uuid)
	mac=$(nvram get et0macaddr | tr -d ':' | tr '[A-Z]' '[a-z]')
	if [ -n "$mac" ]; then
		uuid=${uuid:0:23}
		uuid="$uuid-$mac"
	fi
	nvram set cpeuuid=$uuid
	nvram commit
fi
