#!/bin/sh
#
# Migrate old style vpn to new schema

touch /etc/config/vpnusers

move_user() {
while [ "$(uci get -q $1.@login[-1])" = "login" ]; do
        name=$(uci get -q $1.@login[-1].username)
        pass=$(uci get -q $1.@login[-1].password)
        uci delete $1.@login[-1]
        cfg=$(uci add vpnusers login)
        uci set vpnusers.$cfg.username=$name
        uci set vpnusers.$cfg.password=$pass
done
}

echo "starting"
if [ "$(uci get -q xl2tpd.xl2tpd.enabled)" = "1" ]; then
        echo "xl2tpd is enabled"
        move_user xl2tpd
elif [ "$(uci get -q pptpd.pptpd.enabled)" = "1" ]; then
        move_user pptpd
fi

uci set xl2tpd.xl2tpd.localip=$(uci get network.lan.ipaddr)
ip_range=$(cat /etc/xl2tpd/xl2tpd.conf | sed -n 's/^ip range = //p')
ip_start=$(echo "$ip_range" | cut -d'-' -f1)
ip_end=$(echo "$ip_range" | sed -n 's/.*\.//p')
uci set xl2tpd.xl2tpd.remoteip="$ip_start-$ip_end"

if [ "$(uci get -q luxul.dynamic.vpn)" = "ipsec_enabled" ] ||
   [ "$(uci get -q luxul.dynamic.vpn)" = "l2tp_enabled" ]; then
        uci set ipsec.ipsec.enabled=1
fi
uci set ipsec.ipsec.localip=$(uci get network.lan.ipaddr)
uci set ipsec.ipsec.psk=$(cat /etc/ipsec.secrets | sed -n 's/^%any : PSK //p' | tr -d "\"")
if [ "$(cat /etc/strongswan.conf | sed -n 's/^i_dont_care_about_security_and_use_aggressive_mode_psk = //p')" = "yes" ]; then
        uci set ipsec.ipsec.aggressive=1
fi

uci commit

