#!/bin/sh
#
# Luxul fwman fixup

[ -e "/etc/config/fwman" ] && exit 0
cat > /etc/config/fwman << EOF
config fwman 'basic'
	option repo_url 'http://s3-us-west-2.amazonaws.com/luxul.release/'
	option repo_file 'fw_rev'
EOF
exit 0
