#!/bin/sh
#
# Luxul php.ini fixup

board_id=$(nvram get board_id)
if [ "$board_id" = "luxul_xwr1750_v1" ]; then
	sed -i 's/post_max_size = 8M/post_max_size = 16M/' /etc/php.ini
	sed -i 's/upload_max_filesize = 8M/upload_max_filesize = 16M/' /etc/php.ini

elif [ "$board_id" = "luxul_xbr4500_v1" ]; then
	sed -i 's/post_max_size = 8M/post_max_size = 256M/' /etc/php.ini
	sed -i 's/upload_max_filesize = 8M/upload_max_filesize = 256M/' /etc/php.ini

elif [ "$board_id" = "luxul_xwr1200_v1" ] ||
   [ "$board_id" = "luxul_xwr3100_v1" ] ||
   [ "$board_id" = "luxul_abr4500_v1" ]; then 
	sed -i 's/post_max_size = 8M/post_max_size = 48M/' /etc/php.ini
	sed -i 's/upload_max_filesize = 8M/upload_max_filesize = 48M/' /etc/php.ini
fi

exit 0
