#!/bin/sh /etc/rc.common
# Copyright (C) 2016 luxul.com

START=60
BIN=/usr/sbin/pptpd
CONFIG=/var/etc/pptpd.conf
CHAP_SECRETS=/var/etc/chap-secrets

setup_login() {
	local section="$1"

	config_get username "$section" username
	config_get password "$section" password
	[ -n "$username" ] || return 0
	[ -n "$password" ] || return 0
	echo "$username pptp-server $password *" >> $CHAP_SECRETS
}

start() {
	local enabled
	config_load pptpd

	config_get_bool enabled pptpd enabled '0'
	[ "$enabled" -ne 1 ] && return

	mkdir -p /var/etc
	cp /etc/pptpd.conf $CONFIG

	config_get localip pptpd localip
	config_get remoteip pptpd remoteip
	[ -n "$localip" ] && echo "localip  $localip" >> $CONFIG
	[ -n "$remoteip" ] && echo "remoteip  $remoteip" >> $CONFIG

	config_load vpnusers
	config_foreach setup_login login

	ln -sfn $CHAP_SECRETS /etc/ppp/chap-secrets
	service_start $BIN $OPTIONS -c $CONFIG
}

stop() {
	service_stop $BIN
	echo > $CHAP_SECRETS
}
