#!/bin/sh /etc/rc.common

START=99
STOP=1
USE_PROCD=1

start_service() {
	config_load "TRL"
	config_get_bool enabled TRL enabled 0

	[ $enabled -ne 1 ] && return

	model_lxl=$(uci get -q luxul.static.hw_model)
	model_trl=$(uci get -q TRL.TRL.modelNum)
	[ "$model_trl" != "$model_lxl" ] && {
		uci set TRL.TRL.modelNum=$model_lxl
		uci commit TRL
	}

	procd_open_instance
	procd_set_param command /usr/trl-client/trl-client
	procd_set_param respawn ${threshold:-1} ${timeout:-5} ${retry:-0}

	procd_close_instance
}
