# lighttpd configuration file
#
server.modules = (
       "mod_cgi",
           "mod_access",
           "mod_auth",
           "mod_rewrite",
           "mod_redirect"
)
cgi.assign = ( ".php"  => "/usr/bin/php-cgi" )
server.document-root	= "/www"
server.upload-dirs	= ( "/tmp" )
server.errorlog		= "/var/log/lighttpd/error.log"
server.pid-file		= "/var/run/lighttpd.pid"
index-file.names = ( "index.html", "default.html", "index.htm", "default.htm", "index.php" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
include       "/etc/lighttpd/mime.conf"
url.rewrite-once = (
        "^/(mm.php)" => "$0",
	"^/favicon\.(.*)" => "/public/favicon.ico",
        "^/?(.*)\.(php|css|js|jpg|png|lxl|trx)$" => "$0",
        "^/(.*)$" => "public/index.php?url=$1"
)

$HTTP["url"] !~ "^/fwcache" {
        auth.backend = "plain"
        auth.backend.plain.userfile = "/tmp/auth.conf"
        auth.require = ( "" =>
                (
                "method"  => "basic",
                "realm"   => "Luxul WebAdmin",
                "require" => "valid-user"
                )
        )
}

server.stat-cache-engine = "disable"
etag.use-inode = "disable"
etag.use-mtime = "disable"
etag.use-size = "disable"
static-file.etags = "disable"

