# Allow/Deny
A:*
#/www:admin:password     username/password
# password may be clear text or MD5 cript
/:admin:password
# Mime Types
*.html:/usr/bin/php-cgi
.js:text/javascript
.lxc:text/plain
.log:text/plain
