# strongswan.conf - strongSwan configuration file
#
# Refer to the strongswan.conf(5) manpage for details
#
# Configuration changes should be made in the included files

charon {
        load = sha1 sha2 md5 aes des hmac gmp random nonce xauth-generic attr kernel-netlink socket-default stroke updown farp dhcp

# number of worker threads in charon
threads = 16

i_dont_care_about_security_and_use_aggressive_mode_psk = yes

plugins {
        dhcp    {
                server = 192.168.0.1
                identity_lease = yes
                }
        }
}

dns1 = 192.168.0.1
dns2 = 8.8.8.8
