#!/bin/sh

. /lib/functions.sh

case "$ACTION" in
pressed)
	# Ask for timeout action in 5 seconds
	return 5
;;
timeout)
	# Let user know he can release button now for factory reset
	/sbin/update_leds.sh -f
;;
released)
	if [ "$SEEN" -lt 5 ]; then
		echo -e "\n\n***********************" > /dev/console
		echo        "**** Rebooting Now ****" > /dev/console
		echo -e     "***********************\n\n" > /dev/console
		/sbin/update_leds.sh -r
		sync
		reboot
	elif [ "$SEEN" -gt 5 ]; then
		echo -e "\n\n***********************" > /dev/console
		echo        "**** Factory Reset ****" > /dev/console
		echo -e     "***********************\n\n" > /dev/console
		echo "y" | firstboot
		sync
		reboot
	fi
;;
esac

return 0
